/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitterfake;

import classes.MyTwitter;
import classes.Perfil;
import classes.Tweet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ISAAC
 */
public class SeguirPerfil extends javax.swing.JFrame {

    /**
     * Creates new form SeguirPerfil
     */
    private JFrame parentFrame;
    Boolean segue = false;
    
    public SeguirPerfil() {
        initComponents();
    }
    
    
    public SeguirPerfil(JFrame p, MyTwitter t, Perfil seguidor, Perfil seguido){
        initComponents();
        setLocationRelativeTo(null);
        recebeTwitter(t);
        recebeSeguidor(seguidor);
        recebeSeguido(seguido);
        this.parentFrame = p;
        carregarPerfil();
        carregarTimeLine();
        verificarSeguidor();
    }
    
    MyTwitter twitter;
    Perfil seguidor;
    Perfil seguido;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LNomePerfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LnumeroSeguidores = new javax.swing.JLabel();
        bSeguir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTimeline = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        LNomePerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LNomePerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LNomePerfil.setText("username");

        jLabel1.setText("Seguidores:");

        LnumeroSeguidores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LnumeroSeguidores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LnumeroSeguidores.setText("INFO");

        bSeguir.setText("Seguir");
        bSeguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSeguirMouseClicked(evt);
            }
        });

        tTimeline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tweet", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tTimeline.setToolTipText("");
        jScrollPane1.setViewportView(tTimeline);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSeguir))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(LnumeroSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnumeroSeguidores))
                .addGap(18, 18, 18)
                .addComponent(bSeguir)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSeguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSeguirMouseClicked
        if(segue)
            JOptionPane.showMessageDialog(null, "Você já segue este usuário");
        else{
            twitter.seguir(seguidor.getUsuario(), seguido.getUsuario());
            JOptionPane.showMessageDialog(null, "Agora você está seguindo este usuário");
        }
        
    }//GEN-LAST:event_bSeguirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeguirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeguirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeguirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeguirPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeguirPerfil().setVisible(true);
            }
        });
    }
    
    public void verificarSeguidor(){
        if(seguido.getSeguidores().contains(seguidor)){
            segue = true;
        }
    }
    public void recebeTwitter(MyTwitter t){
        twitter = t;
    }
    
    public void recebeSeguidor(Perfil p){
        seguidor = p;
    }
    
    public void recebeSeguido(Perfil p){
        seguido = p;
    }
    
    public void carregarPerfil(){
        String usuario = seguido.getUsuario();
        int n = twitter.numeroSeguidores(usuario);
        LNomePerfil.setText(usuario);
        LnumeroSeguidores.setText(String.valueOf(n));
    }
    
    
    public void carregarTimeLine() {
        ArrayList<Tweet> timeline = twitter.timeline(seguido.getUsuario());
        
        DefaultTableModel modelo = (DefaultTableModel)tTimeline.getModel(); 
        modelo.setNumRows(0);
        int cont = timeline.size();
        for(int i = 0; i<cont; i++){
                Tweet t = timeline.get(i);
                
                modelo.addRow(new Object[]{
                    t.getMensagem(),
                    t.getUsuario(),
                });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNomePerfil;
    private javax.swing.JLabel LnumeroSeguidores;
    private javax.swing.JButton bSeguir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tTimeline;
    // End of variables declaration//GEN-END:variables
}
