/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitterfake;

import classes.MyTwitter;
import classes.Perfil;
import classes.Tweet;
import exceptions.PDException;
import exceptions.PIException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ISAAC
 */
public class ViewPerfil extends javax.swing.JFrame {

    /**
     * Creates new form ViewPerfil
     */
    
    private JFrame parentFrame;
    NovoTweet novoTweet;
    SeguirPerfil seguirPerfil;
    
    public ViewPerfil() {
        initComponents();
    }
    
    public ViewPerfil(JFrame p, MyTwitter t, Perfil perfil){
        initComponents();
        setLocationRelativeTo(null);
        recebeTwitter(t);
        recebePerfil(perfil);
        this.parentFrame = p;
        carregarPerfil();
        carregarTimeLine();
    }
    
    MyTwitter twitter;
    Perfil perfil;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LNomePerfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LnumeroSeguidores = new javax.swing.JLabel();
        bSearch = new javax.swing.JButton();
        jSearchPerfil = new javax.swing.JTextField();
        bNovoTweet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTimeline = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        LNomePerfil.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LNomePerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LNomePerfil.setText("username");

        jLabel1.setText("Seguidores:");

        LnumeroSeguidores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LnumeroSeguidores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LnumeroSeguidores.setText("INFO");

        bSearch.setText("Ok");
        bSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSearchMouseClicked(evt);
            }
        });

        bNovoTweet.setText("Novo Tweet");
        bNovoTweet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bNovoTweetMouseClicked(evt);
            }
        });

        tTimeline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tweet", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tTimeline.setToolTipText("");
        jScrollPane1.setViewportView(tTimeline);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bNovoTweet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSearchPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(LnumeroSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNomePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnumeroSeguidores))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNovoTweet)
                    .addComponent(jSearchPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSearch))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoTweetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bNovoTweetMouseClicked
        novoTweet = new NovoTweet(ViewPerfil.this, twitter, perfil);
        novoTweet.setVisible(true);
    }//GEN-LAST:event_bNovoTweetMouseClicked

    private void bSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSearchMouseClicked
        Perfil u = twitter.repusuarios.buscar(jSearchPerfil.getText());
        if(u == null)
            JOptionPane.showMessageDialog(null, "Usuário não encontrado", "Erro ao buscar usuário", JOptionPane.ERROR_MESSAGE);
        else{
            seguirPerfil = new SeguirPerfil(ViewPerfil.this, twitter, perfil, u);
            seguirPerfil.setVisible(true);
        }
    }//GEN-LAST:event_bSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPerfil().setVisible(true);
            }
        });
    }
    
    public void recebeTwitter(MyTwitter t){
        twitter = t;
    }
    
    public void recebePerfil(Perfil p){
        perfil = p;
    }
    
    public void carregarPerfil(){
        String usuario = perfil.getUsuario();
        int n = twitter.numeroSeguidores(usuario);
        LNomePerfil.setText(usuario);
        LnumeroSeguidores.setText(String.valueOf(n));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNomePerfil;
    private javax.swing.JLabel LnumeroSeguidores;
    private javax.swing.JButton bNovoTweet;
    private javax.swing.JButton bSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchPerfil;
    private javax.swing.JTable tTimeline;
    // End of variables declaration//GEN-END:variables

    public void carregarTimeLine() {
        ArrayList<Tweet> timeline = null;
        try {
            timeline = twitter.timeline(perfil.getUsuario());
        } catch (PIException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao carregar timeline", JOptionPane.ERROR_MESSAGE);
        } catch (PDException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao carregar timeline", JOptionPane.ERROR_MESSAGE);
        }
        
        DefaultTableModel modelo = (DefaultTableModel)tTimeline.getModel(); 
        modelo.setNumRows(0);
        int cont = timeline.size();
        for(int i = 0; i<cont; i++){
                Tweet t = timeline.get(i);
                
                modelo.addRow(new Object[]{
                    t.getMensagem(),
                    t.getUsuario(),
                });
        }
    }
}
